class ActiveScaffold::AssignmentTitlesController < ApplicationController
  
#The following code customizes the interface generated by the active scaffold plugin.  
  layout "activescaffold"
  
  active_scaffold :assignment_title do |config|
    #displays table name as "Assignment Titles"
    config.label = "Assignment Titles"
    
    #orders columns
    config.columns = [:id, :name, :assignment_type, :commissioned, :temporary, :notes, :assignments, :updated_at, :created_at]
    
    #adds search functionality for the following fields
    config.columns[:assignment_type].search_sql = 'assignment_types.name'
    config.search.columns << :assignment_type
    
    config.search.columns << :notes
  
  end
  
end
