class ActiveScaffold::AssignmentsController < ApplicationController
  
#The following code customizes the interface generated by the active scaffold plugin.
  layout "activescaffold"
  
  active_scaffold :assignment do |config|
    #displays table name as Assignments
    config.label = "Assignments"
    
    #orders the columns
    config.columns = [:id, :location, :assignment_title, :individual, :start_year, :start_certain, :end_year, :end_certain, :notes, :validations]
    
    #adds search functionality for the following columns
    config.columns[:assignment_title].search_sql = 'assignment_titles.name'
    config.search.columns << :assignment_title
  
    config.columns[:individual].search_sql = 'individuals.name'
    config.search.columns << :individual
    
    config.columns[:location].search_sql = 'locations.name'
    config.search.columns << :location
    
    config.search.columns << :start_year
    
    config.search.columns << :end_year
    
    config.search.columns << :notes
  end
  
end
