class ActiveScaffold::CitationsController < ApplicationController

#The following code customizes the interface generated by the active scaffold plugin.
  layout "activescaffold"
  
  active_scaffold :citation do |config|
    config.label = "Citations"
    config.columns[:bibliography].label = "Source"
    config.columns[:pages].label = "Page Number"
    config.columns = [:id, :title, :bibliography, :pages, :canonic_url, :notes, :created_at, :updated_at]
  end
end
