class ActiveScaffold::ContinentsController < ApplicationController
  
#The following code customizes the interface generated by the active scaffold plugin.
  layout "activescaffold"
  
  active_scaffold :continent do |config|
    
    #displays table name as "Continents"
    config.label = "Continents"
    
    #renames the states table to avoid confusion
    config.columns[:states].label = "Countries/ Territories/ Colonies"
    
    #orderst the columns
    config.columns = [:id, :name, :states, :created_at, :updated_at]
    
    #adds search functionality for the following columns
    config.columns[:states].search_sql = 'states.name'
    config.search.columns << :states
    
  end
end
