class ActiveScaffold::EmpiresController < ApplicationController
  
#The following code customizes the interface generated by the active scaffold plugin.  
  layout "activescaffold"
  
  active_scaffold :empire do |config|
    config.label = "Empires"
    config.columns = [:name, :in_empires, :notes, :created_at, :updated_at]
  end  
end
