class ActiveScaffold::EnclosuresController < ApplicationController
  
  #The following code customizes the interface generated by the active scaffold plugin.  
    layout "activescaffold"
    
    active_scaffold :enclosure do |config|
      config.columns = [:main_letter, :enclosed_letter, :notes, :validations, :created_at, :updated_at]

    end
end
