class ActiveScaffold::InRegionsController < ApplicationController
  
#The following code customizes the interface generated by the active scaffold plugin.  
  layout "activescaffold"
  
  active_scaffold :in_region do |config|
    config.label = "In Regions: Linking Table for Regions and Locations"
    config.columns = [:id, :region, :location, :notes, :created_at, :updated_at]
  end
end
