class ActiveScaffold::InStatesController < ApplicationController

#The following code customizes the interface generated by the active scaffold plugin.
  layout "activescaffold"
  
  active_scaffold :in_state do |config|
    
    #displays table name as "In States: Linking Table for Locations and States"
    config.label = "In States: Linking Table for Locations and States"
    
    #orders columns
    config.columns = [:location, :state, :start_year, :end_year, :notes, :updated_at, :created_at]
    
    #adds search functionality for the following columns
    config.columns[:location].search_sql = 'locations.name'
    config.search.columns << :location
    
    config.columns[:state].search_sql = 'states.name'
    config.search.columns << :state
    
    config.search.columns << :start_year
    
    config.search.columns << :end_year
    
    config.search.columns << :notes
    
  end
end
