class ActiveScaffold::LocationsController < ApplicationController

#The following code customizes the interface generated by the active scaffold plugin.
  layout "activescaffold"
  
  active_scaffold :location do |config|
    #orders the columns
    config.columns = [:id, :name, :in_states, :in_regions, :lat, :long, :notes, :assignments, :letters, :organizations, :residences, :updated_at, :created_at]
    
    #adds search functionality for the following columns
    config.search.columns << :notes
    
  end
end
