class ActiveScaffold::MembersController < ApplicationController
  
#The following code customizes the interface generated by the active scaffold plugin.  
  layout "activescaffold"
  
  active_scaffold :member do |config|
    config.label = "Members of Organizations"
    config.columns = [:individual, :organization, :role, :start_year, :end_year, :notes, :created_at, :updated_at]
  end
end
