class ActiveScaffold::OccupationsController < ApplicationController
  
#The following code customizes the interface generated by the active scaffold plugin.  
  layout "activescaffold"
  
  active_scaffold :occupation do |config|
    config.label = "Occupations"
    config.columns = [:occupation_title, :individual, :start_year, :end_year, :notes, :created_at, :updated_at]
  end
end
