class ActiveScaffold::OccupationTitlesController < ApplicationController
  
#The following code customizes the interface generated by the active scaffold plugin.  
  layout "activescaffold"
  
  active_scaffold :occupation_title do |config|
    config.label = "Occupation Titles"
    config.columns = [:id, :name, :occupation_type, :notes, :occupations, :created_at, :updated_at]
  end
end
