class ActiveScaffold::OrganizationTypesController < ApplicationController
  
#The following code customizes the interface generated by the active scaffold plugin.  
  layout "activescaffold"
  
  active_scaffold :organization_type do |config|
    config.label = "Organization Types"
    config.columns = [:name, :notes, :organizations, :created_at, :updated_at]
  end
end
