class ActiveScaffold::RegionsController < ApplicationController
  
#The following code customizes the interface generated by the active scaffold plugin.  
  layout "activescaffold"
  
  active_scaffold :region do |config|
    config.label = "Regions"
    config.columns = [:id, :name, :in_regions, :notes, :created_at, :updated_at]
  end
end
