class ActiveScaffold::ResidenceTypesController < ApplicationController
  
#The following code customizes the interface generated by the active scaffold plugin.  
  layout "activescaffold"
  
  active_scaffold :residence_type do |config|
    config.label = "Residence Types"
    config.columns[:temporary].label = "Temporary (y/n)"
    config.columns = [:name, :temporary, :notes, :residences, :created_at, :updated_at]
  end
end
