class ActiveScaffold::StatesController < ApplicationController
  
#The following code customizes the interface generated by the active scaffold plugin.  
  layout "activescaffold"
  
  active_scaffold :state do |config|
    #displays table name as "States"
    config.label = "States"
    
    #displays in_states field as Contains Locations
    config.columns[:in_states].label = "Contains Locations"
    
    #orders columns
    config.columns = [:name, :continent, :notes, :in_states, :in_empires, :individuals, :created_at, :updated_at]
    
    #adds search functionality for the following columns
    config.columns[:continent].search_sql = 'continents.name'
    config.search.columns << :continent
    
    config.search.columns << :notes
  end
end
