class ActiveScaffold::ValidationsController < ApplicationController
  
  #The following code customizes the interface generated by the active scaffold plugin.  
    layout "activescaffold"

    active_scaffold :validation do |config|
      #displays table name as "States"
      config.label = "Validations"

      #displays in_states field as Contains Locations
      config.columns[:user].label = "Entered By"
      config.columns[:validatable_type].label = "Validatable Type"
      config.columns[:validatable_id].label = "Validatable Id"
      config.columns[:supports].label = "Supports?"

      config.list.columns.exclude :validatable_type, :entity_id
      config.list.columns << :validated_record
      
      config.columns << :validated_record
      
      #orders columns
      config.columns = [:id, :citation, :supports, :validatable_type, :validatable_id, :user, :notes, :created_at, :updated_at]
      
      #orders columns in the default list
      config.list.columns = [:id, :citation, :supports, :validated_record, :user, :notes, :created_at, :updated_at]

      #adds search functionality for the following columns
      config.columns[:citation].search_sql = 'citations.title'
      config.search.columns << :citation

      config.search.columns << :notes
      
      config.search.columns << :validatable_type
      
      config.search.columns << :user
      
      config.search.columns << :validatable_id
    end
end
